import { Header } from "@/layout/Header/Header"
import "./globals.css"
import { Plus_Jakarta_Sans as PlusJakartaSans } from "next/font/google"

const plusJakartaSans = PlusJakartaSans({
  subsets: ["latin"],
  weight: ["200", "400", "300", "500", "600", "700", "800"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
